### PR TITLE
Add inline and hot module replacement

### PR DESCRIPTION
**Pull request by chiplay**
Address https://github.com/webpack/grunt-webpack/issues/36

### CODE REVIEW

**Comment by sokra** [comment]
Looks good.

**Comment by chiplay** [comment]
@sokra any chance this could get merged in soon? Thanks!

**Comment by sokra** [comment]
@chiplay Do you want to maintain this grunt plugin? I don't have the time to maintain it enough.

**Comment by chiplay** [comment]
@sokra sounds good - would love to help out! 

We are just getting ramped up with Webpack at our company, but really love it so far. Thanks so much for all your amazing work and commitment with the project.

**Comment by sokra** [comment]
btw. you made a PR against your own repo, not against the webpack/grunt-webpack repo.

**Comment by chiplay** [comment]
Yea, didn't mean to do that.  It's a PR on the webpack/grunt-webpack as well

**Pull request merged**
